# Generated by Django 4.2.6 on 2023-12-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_ended',
            field=models.DateTimeField(null=True),
        ),
    ]
