# Generated by Django 4.2.6 on 2023-12-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_test_date_ended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='date_ended',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='type',
            new_name='script',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='date_started',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='test',
            name='code_line',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='engineer',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='test',
            name='fail_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='Tester1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='technician',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
