# Generated by Django 4.2.6 on 2023-12-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_date_ended_test_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='program',
            field=models.CharField(default='program1', max_length=100),
            preserve_default=False,
        ),
    ]
